### ISSUE TITLE
Consider aliasing/renaming some API functions

### ISSUE THREAD

**Issue by Alok** [williamFalcon/test-tube#14]
Some function names are a bit verbose. It'd be nice to at least alias the following:

- `add_metric_row -> add (or log)` since that carries the same meaning and is a lot shorter
- `add_opt_argument_list -> add_argument_list`
- `add_opt_argument_range -> add_argument_range`

**Comment by williamFalcon** [comment]
Good suggestions. I do worry about just “add” being a bit ambiguous. What about “add_row”?

**Comment by williamFalcon** [comment]
@Alok thanks for adding!
