### ISSUE TITLE
Wrong directory for logging

### ISSUE THREAD

**Issue by rcmalli** [williamFalcon/test-tube#52]
https://github.com/williamFalcon/test-tube/blob/3d4ce061de239f37e34f80bd691bd8940ddc5020/test_tube/log.py#L516

This line makes the `EventWriter` to save logs to `save_dir` rather than `log_dir` which leaves the `tf` folder empty.

This may be related to new Pytorch update since I am using `v1.2`

<img width="271" alt="image" src="https://user-images.githubusercontent.com/7341604/62825780-c9c53800-bbb9-11e9-8fe9-af158d041d42.png">

**Comment by williamFalcon** [comment]
@rcmalli good catch!

**Comment by rcmalli** [comment]
It looks working. Thanks. 👍
