### ISSUE TITLE
Add tensorboardx integration

### ISSUE THREAD

**Issue by williamFalcon** [williamFalcon/test-tube#7]
Add Tensorboardx integration
(https://github.com/lanpa/tensorboard-pytorch)

**Comment by zafarali** [comment]
What do you envision tensorboard support to look like? Would you wrap the Experiment API with tensorboardx internals?

**Comment by williamFalcon** [comment]
Yup! The goal would be to leave Experiment as is and do whatever formatting / saving that tensorboardx requires under the hood so that the experiment data can be read by it.   

In short:
1. Implement saving / formatting under the hood of the Experiment API.
2. Add whatever APIs to experiment that map to tensorboardx logging APIs. It would be even better if the .log .tag, etc... APIs just worked automatically without having to add new APIs for tensorboardx.

I built a GUI that works on test tube stuff (still developing it and haven't had much time to work on it), but would be great to enable any viz library to work with test-tube, and many people use tensorboardx already...

Happy to jump on a hangouts to discuss if you're interested in working on this!

**Comment by zafarali** [comment]
I'm going to be using test_tube in one of my own projects for
hyperparameter searching, I'll see if i can make some of these
contributions while working with it!

**Comment by williamFalcon** [comment]
awesome! make sure to issue out PRs for discrete functionality so it can make reviewing a lot easier.

**Comment by williamFalcon** [comment]
I also just found out about https://github.com/PaddlePaddle/VisualDL, wondering if that's also a good option.

**Comment by zafarali** [comment]
That looks really cool. I wonder if it solve the number 1 problem with
tensorboard which is slowness.

I think the key here would be to add a nice `Visualize` component that can
stream to tensorboard, visualDL or comet.ml which people I collaborate with
seem to enjoy using.
